title:             lishuhang.me
email:             your-email@example.com
description:       Test Jekyll Blog
author:            Start Bootstrap
baseurl:           "/blog1"
url:               "http://lishuhang.github.io/blog1"

# Social Profiles
twitter_username:  lishuhang
github_username:   lishuhang
facebook_username: lishuhang

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"s
plugins:
  - jekyll-feed
  - jekyll-paginate
